# Generated by Django 4.2.7 on 2024-01-06 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopCarts',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('paid', models.BooleanField(default=True)),
                ('delivered', models.BooleanField(blank=True, default=False, null=True)),
                ('order_status', models.CharField(choices=[('未處理', '未處理'), ('處理中', '處理中'), ('寄送中', '寄送中'), ('已寄送', '已寄送'), ('已送達', '已送達')], default='未處理', max_length=10)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
