# Generated by Django 4.2.7 on 2023-11-25 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_product_name_alter_product_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pwd',
        ),
    ]
