# Generated by Django 4.2.7 on 2024-01-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_shopcarts_shopcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='product',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
