# Generated by Django 4.2.7 on 2024-01-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productss',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
