# Generated by Django 4.2.7 on 2024-01-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_productss_delete_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productss',
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
